server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifebit_db
    username: lifebit_user
    password: lifebit_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allowed-headers: "*"
        allow-credentials: true
  endpoint:
    health:
      show-details: always